### ISSUE TITLE
Thank you!... and how to deal with it?

### ISSUE THREAD

**Issue by hopehopehope** [hacksparrow/virus#1]
Thank you for this demonstration!
Allthough I am still quite new to the whole node.js thing it seems to me that very little concern is given to the negative effects of running node.js with untrusted scripts.

Can you tell some solution, that would i.e. avoid the effect of your example-virus to happen? http://gf3.github.io/sandbox/ seems interesting....
surely not the solution.

I wonder what having node.js run on my pretty insecure ubuntu 12.04 can have as a risk?

**Comment by hacksparrow** [comment]
Currently there are no reliable solutions :) If someone hacked the GitHub / npm account of a popular npm package, we are all screwed. And here is the bomb: it is only a matter of time someone did that. Har har!
